subjects: ['1', '2', '3', '4', '5', '6', '8',  '9', '10', '12', '13', '14',
           '601', '0502', '503', '504', '505', '506', '508', '907', '610', 
           '612', '513', '514']
# who has listening difficulty?
lis_diff: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

use_deconv: true

age_matching:
  '1': '601'
  '2': '0502'
  '3': '503'
  '4': '504'
  '5': '505'
  '6': '506'
  '8': '508'
  '9': '907'
  '10': '610'
  '12': '612'
  '13': '513'
  '14': '514'

# trial epoch extents
t_min: -0.5
t_max: 5.9

# t_max of pupil response kernel estimated at LABS^N; see
# http://dx.doi.org/10.1121/1.4943787
t_peak: 0.512


# reaction time limits
rt_min: 0.1
rt_max: 0.8

subset_names:
  ldiff: listening difficulty
  control: age-matched controls
  all: all subjects

spatial_mapping:
  -30x30: LR
  -30x-30: LL
  30x-30: RL
  30x30: RR

talker_mapping:
  male-male: MM
  female-female: FF
  male-female: MF
  female-male: FM
